# Site settings
title: Patrick's Blog
description: Ramblings of a software developer
author: Patrick Klaeren
github_username: patrickklaeren
twitter_username: patrickklaeren
rss: RSS
header_pages:
  - about.md
  - tags/index.html
paginate: 7
paginate_path: "/page/:num/"
show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
